//! Golden vectors generated by Go's own marshaler (Accumulate 1.4.6.7, commit e1d1db9).
//! Fixture: tests/fixtures/accumulate_1_4_6_7_vectors.json
//!
//! Binary encoding is consensus-critical: every vector must match byte-for-byte, and transaction
//! hashes must match Go's `Transaction.GetHash()`. If one fails, the SDK's marshaling disagrees
//! with the network - a consensus-visible bug, not a fixture to update.
//!
//! The vectors' own JSON is fed to the SDK, so this exercises the same path a co-signer takes when
//! it recomputes a hash from a received envelope.

use accumulate_client::codec::signing::compute_transaction_hash;
use accumulate_client::generated::enums::HashAlgorithm;
use accumulate_client::generated::header::HashLockOptions;
use accumulate_client::generated::types::NetworkGlobals;
use accumulate_client::helpers::{
    marshal_body_for_test, marshal_header_from_json, HeaderOptions, SmartSigner, TxBody,
};
use accumulate_client::{AccOptions, AccumulateClient};
use serde_json::{json, Value};

fn vectors() -> Vec<Value> {
    let raw = include_str!("fixtures/accumulate_1_4_6_7_vectors.json");
    serde_json::from_str(raw).expect("fixture parses")
}

fn named(prefix: &str) -> Vec<Value> {
    vectors()
        .into_iter()
        .filter(|v| v["name"].as_str().unwrap().starts_with(prefix))
        .collect()
}

fn vec_by_name(name: &str) -> Value {
    vectors().into_iter().find(|v| v["name"] == name).unwrap_or_else(|| panic!("missing {name}"))
}

#[test]
fn headers_match_go() {
    let all = named("header_");
    assert!(all.len() >= 9, "expected all header vectors, got {}", all.len());
    for v in all {
        let got = hex::encode(marshal_header_from_json(&v["json"]).unwrap());
        assert_eq!(got, v["binaryHex"].as_str().unwrap(), "{}", v["name"]);
    }
}

#[test]
fn hash_lock_options_match_go() {
    for v in named("hashlockoptions_") {
        let opts: HashLockOptions = serde_json::from_value(v["json"].clone()).unwrap();
        let got = hex::encode(opts.to_binary().unwrap().marshal());
        assert_eq!(got, v["binaryHex"].as_str().unwrap(), "{}", v["name"]);
    }
}

#[test]
fn transaction_hashes_match_go() {
    // SyntheticDepositTokens is a system-generated type this SDK never builds or signs.
    let skip = ["tx_syntheticdeposittokens"];
    let mut checked = 0;
    for v in named("tx_") {
        let name = v["name"].as_str().unwrap();
        if skip.contains(&name) {
            continue;
        }
        let header = marshal_header_from_json(&v["json"]["header"]).unwrap();
        let body = marshal_body_for_test(&v["json"]["body"]).unwrap();
        assert_eq!(
            hex::encode(compute_transaction_hash(&header, &body)),
            v["hashHex"].as_str().unwrap(),
            "{name}"
        );
        checked += 1;
    }
    // sendtokens plain + hashlock, releaselockedoperation, syntheticlockeddeposit
    assert_eq!(checked, 4);
}

#[test]
fn transaction_type_codes() {
    use accumulate_client::codec::signing::tx_types;
    assert_eq!(tx_types::RELEASE_LOCKED_OPERATION, 0x18);
    assert_eq!(tx_types::SYNTHETIC_LOCKED_DEPOSIT, 0x37);
}

#[test]
fn network_globals_block_interval() {
    // NOTE: this generated struct uses the Go field names (PascalCase) and string-typed schedule
    // fields, which is not the shape the node's JSON has; the test uses the struct's own shape.
    let base = json!({
        "OperatorAcceptThreshold": {"Numerator": 2, "Denominator": 3},
        "ValidatorAcceptThreshold": {"Numerator": 2, "Denominator": 3},
        "MajorBlockSchedule": "0 */12 * * *",
        "AnchorEmptyBlocks": true,
        "FeeSchedule": {"CreateIdentitySliding": "", "CreateSubIdentity": "0", "BareIdentityDiscount": "0"},
        "Limits": {"DataEntryParts": 0, "AccountAuthorities": 0, "BookPages": 0, "PageEntries": 0,
                   "IdentityAccounts": 0, "PendingMajorBlocks": 0, "EventsPerBlock": 0}
    });

    // older networks do not report it
    let old: NetworkGlobals = serde_json::from_value(base.clone())
        .unwrap_or_else(|e| panic!("NetworkGlobals should parse without BlockInterval: {e}"));
    assert_eq!(old.block_interval, None);

    // the node emits a duration as {seconds, nanoseconds}
    let mut with = base;
    with["BlockInterval"] = json!({"seconds": 1, "nanoseconds": 500000000});
    let g: NetworkGlobals = serde_json::from_value(with).unwrap();
    assert_eq!(g.block_interval, Some(json!({"seconds": 1, "nanoseconds": 500000000})));
    // ...and it survives a round trip
    let again: NetworkGlobals = serde_json::from_value(serde_json::to_value(&g).unwrap()).unwrap();
    assert_eq!(again, g);
}

fn lock(alg: HashAlgorithm, len: usize, expiration: Option<i64>) -> HashLockOptions {
    HashLockOptions::new(alg, vec![7u8; len], expiration)
}

#[test]
fn hash_lock_validate_for_submit_mirrors_node() {
    let now = 1_900_000_000;
    let (min, day) = (60, 86_400);
    for ok in [
        lock(HashAlgorithm::Sha256, 32, Some(now + 60 * min)),
        lock(HashAlgorithm::Sha256D, 32, Some(now + 30 * day)),
        lock(HashAlgorithm::Hash160, 20, Some(now + 10 * min)),
    ] {
        ok.validate_for_submit(now).unwrap();
    }
    for (why, bad) in [
        ("wrong length for sha256", lock(HashAlgorithm::Sha256, 20, Some(now + 60 * min))),
        ("wrong length for hash160", lock(HashAlgorithm::Hash160, 32, Some(now + 60 * min))),
        ("unknown algorithm", lock(HashAlgorithm::Unknown, 32, Some(now + 60 * min))),
        ("missing expiration", lock(HashAlgorithm::Sha256, 32, None)),
        ("expires too soon", lock(HashAlgorithm::Sha256, 32, Some(now + 9 * min))),
        ("expires too late", lock(HashAlgorithm::Sha256, 32, Some(now + 31 * day))),
    ] {
        assert!(bad.validate_for_submit(now).is_err(), "{why} should be rejected");
    }
}

#[test]
fn release_locked_operation_helper() {
    let body = TxBody::release_locked_operation("acc://ab@alice.acme/tokens", b"secret");
    assert_eq!(body["type"], "releaseLockedOperation");
    assert_eq!(body["preimage"], hex::encode(b"secret"));
}

/// Signing with every header option must hash the fields it puts in the envelope, and a
/// co-signer who recomputes the hash from that envelope (after a JSON hand-off) must agree.
#[tokio::test]
async fn signed_envelope_hash_covers_every_header_field() {
    use accumulate_client::generated::header::{ExpireOptions, HoldUntilOptions};

    let client = AccumulateClient::new_with_options(
        url::Url::parse("http://localhost:26660/v2").unwrap(),
        url::Url::parse("http://localhost:26660/v3").unwrap(),
        AccOptions::default(),
    )
    .await
    .unwrap();
    let key = ed25519_dalek::SigningKey::from_bytes(&[7u8; 32]);
    let signer = SmartSigner::new(&client, key, "acc://alice.acme/book/1");

    let options = HeaderOptions {
        memo: Some("all".into()),
        metadata: Some(vec![9]),
        expire: Some(ExpireOptions { at_time: Some(1_900_000_000) }),
        hold_until: Some(HoldUntilOptions { minor_block: Some(5) }),
        authorities: Some(vec!["acc://auth1.acme/book".into()]),
        hash_lock: Some(TxBody::hash_lock(HashAlgorithm::Sha256, vec![1u8; 32], 1_950_000_000)),
    };
    let body = TxBody::send_tokens_single("acc://bob.acme/tokens", "12345");
    let envelope = signer.sign_with_options("acc://alice.acme/tokens", &body, &options).unwrap();

    // hand-off: serialize and re-read, as a co-signer would
    let received: Value = serde_json::from_str(&serde_json::to_string(&envelope).unwrap()).unwrap();
    let tx = &received["transaction"][0];
    for f in ["expire", "holdUntil", "authorities", "hashLock", "memo", "metadata"] {
        assert!(tx["header"].get(f).is_some(), "header lost {f}");
    }
    let header = marshal_header_from_json(&tx["header"]).unwrap();
    let body_bytes = marshal_body_for_test(&tx["body"]).unwrap();
    assert_eq!(
        hex::encode(compute_transaction_hash(&header, &body_bytes)),
        received["signatures"][0]["transactionHash"].as_str().unwrap()
    );
}

#[test]
fn v3_receipt_parses_new_fields_and_tolerates_old_responses() {
    use accumulate_client::Receipt;

    let r: Receipt = serde_json::from_value(json!({
        "start": "ab", "end": "cd", "anchor": "ef",
        "entries": [{"right": true, "hash": "01"}],
        "localBlock": 12, "localBlockTime": "2030-01-02T03:04:05Z", "majorBlock": 3,
        "forHeight": 9, "complete": false, "partition": "bvn0", "startsAtMainState": true
    }))
    .unwrap();
    assert_eq!(r.for_height, 9);
    assert!(!r.complete);
    assert_eq!(r.partition.as_deref(), Some("bvn0"));
    assert!(r.starts_at_main_state);
    assert_eq!(r.receipt.entries.len(), 1);

    // an older node's response has none of the new fields
    let old: Receipt = serde_json::from_value(json!({
        "start": "ab", "end": "cd", "anchor": "ef", "localBlock": 12, "majorBlock": 3
    }))
    .unwrap();
    assert_eq!(old.for_height, 0);
    assert!(!old.starts_at_main_state);
    assert_eq!(old.partition, None);
}

#[test]
fn v3_proof_service_options() {
    use accumulate_client::{AnchorReceiptOptions, MajorHeaderRangeOptions, MinorRootRangeOptions};

    assert_eq!(
        json!(MajorHeaderRangeOptions { partition: "Directory".into(), start: 1, end: 4 }),
        json!({"partition": "Directory", "start": 1, "end": 4})
    );
    assert_eq!(
        json!(MinorRootRangeOptions { partition: "Directory".into(), since: 10, until: 0 }),
        json!({"partition": "Directory", "since": 10, "until": 0})
    );
    let a = AnchorReceiptOptions::new("bvn0", &[1u8; 32], 3);
    assert_eq!(
        json!(a),
        json!({"partition": "bvn0", "bptRoot": "01".repeat(32), "atOrAfter": 3})
    );
    a.validate().unwrap();
    // atOrAfter is omitted when zero
    assert!(json!(AnchorReceiptOptions::new("bvn0", &[1u8; 32], 0)).get("atOrAfter").is_none());
    let bad = AnchorReceiptOptions { partition: "bvn0".into(), bpt_root: "abcd".into(), at_or_after: 0 };
    assert!(bad.validate().is_err());
}
