[env]
# Environment variables for coverage collection
CARGO_INCREMENTAL = "0"
RUSTFLAGS = "-C instrument-coverage"
LLVM_PROFILE_FILE = "cargo-test-%p-%m.profraw"

[alias]
# Coverage collection aliases
cov = "llvm-cov --all-features --workspace --lcov --output-path target/lcov.info"
cov-report = "llvm-cov --all-features --workspace --html"
cov-open = "llvm-cov --all-features --workspace --open"
cov-clean = "llvm-cov clean"

# Quality gate aliases
quality = ["test", "--test", "no_todos"]
coverage-gate = "llvm-cov --all-features --workspace --lcov --output-path target/lcov.info"
