# Rust formatting configuration for Accumulate SDK
# Based on Rust 2021 edition standards

edition = "2021"

# Line width and indentation
max_width = 100
hard_tabs = false
tab_spaces = 4

# Import formatting
imports_granularity = "Crate"
imports_layout = "Vertical"
group_imports = "StdExternalCrate"
reorder_imports = true

# Function and control flow formatting
fn_single_line = false
where_single_line = false
force_explicit_abi = true
empty_item_single_line = true
struct_lit_single_line = true
fn_params_layout = "Tall"
brace_style = "SameLineWhere"
control_brace_style = "AlwaysSameLine"

# Comments and documentation
wrap_comments = true
format_code_in_doc_comments = true
normalize_comments = true
normalize_doc_attributes = true
doc_comment_code_block_width = 80

# String and macro formatting
format_strings = false
format_macro_matchers = true
format_macro_bodies = true

# Trailing punctuation
trailing_comma = "Vertical"
trailing_semicolon = true
match_block_trailing_comma = false

# Spacing and newlines
spaces_around_ranges = false
binop_separator = "Front"
remove_nested_parens = true
combine_control_expr = true
struct_field_align_threshold = 0
array_width = 60
attr_fn_like_width = 70
chain_width = 60
single_line_if_else_max_width = 50

# Advanced formatting options
condense_wildcard_suffixes = false
force_multiline_blocks = false
format_generated_files = true
hex_literal_case = "Preserve"
merge_derives = true
use_field_init_shorthand = false
use_try_shorthand = false

# Stability options (when available)
unstable_features = false