// GENERATED BY Accumulate gen-sdk. DO NOT EDIT.

//! Accumulate Rust SDK
//!
//! A Rust client library for the Accumulate blockchain JSON-RPC API .
//!
//! ## Usage
//!
//! ```rust,no_run
//! use accumulate_client::AccumulateClient;
//!
//! #[tokio::main]
//! async fn main() -> Result<(), Box<dyn std::error::Error>> {
//!     let client = AccumulateClient::new("https://mainnet.accumulatenetwork.io");
//!
//!     let status = client.status().await?;
//!     println!("Node status: {:?}", status);
//!
//!     Ok(())
//! }
//! ```

pub mod client;
pub mod json_rpc_client;
pub mod types;

pub use client::AccumulateClient;
pub use json_rpc_client::{JsonRpcClient, JsonRpcError};
pub use types::*;